name: Masisokits
main: com.tuserver.masisokits.MasisoKits
version: 1.0.9
api-version: 1.20
author: Cristian

commands:
  masisokit:
    description: Comando principal de MasisoKits
    usage: /masisokit <subcomando>
    permission: masisokits.use

permissions:
  masisokits.use:
    default: true
  masisokits.reset:
    default: op
  masisokits.reload:
    default: op
  masisokits.kit.*:
    description: Permite reclamar cualquier kit
    default: false
